template_src = "~/yosupo-library/src/yosupo/template.cpp"
compile_debug = """
{{.CXX}} {{.Source}} -o {{.Output}} \
-std=c++20 -g -DYOSUPO_LOCAL -march=native \
-Wall -Wextra -Wshadow -Wconversion -Wno-sign-conversion -Wno-unused-variable \
-fsanitize=address,undefined -fno-omit-frame-pointer \
-I ~/Algorithm/src \
-I ~/ac-library \
-I ~/yosupo-library/src \
-I ~/fastfps/src
"""
compile_opt = """
{{.CXX}} {{.Source}} -o {{.Output}} \
-std=c++20 -g -DYOSUPO_LOCAL -O2 -march=native \
-Wall -Wextra -Wshadow -Wconversion -Wno-sign-conversion -Wno-unused-variable \
-I ~/Algorithm/src \
-I ~/ac-library \
-I ~/yosupo-library/src \
-I ~/fastfps/src
"""
bundle_source = """
oj-bundle {{.Source}} \
-I ~/Algorithm/src \
-I ~/ac-library \
-I ~/yosupo-library/src \
-I ~/fastfps/src
> {{.Output}}
"""

pbcopy = "pbcopy"
